/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import common.PredefineMethods;
import java.sql.SQLException;

/**
 *
 *
 */
public class Dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dashboard2
     */
    public Dashboard() throws SQLException {
        initComponents();
        PredefineMethods.tableload("SELECT name,type,quantity FROM fertilizer WHERE quantity<=10", jTable1);
        PredefineMethods.tableload("SELECT name,type,quantity FROM chemical WHERE quantity<=10", jTable2);
//        jLabel8.setText( PredefineMethods.viewDBValue("SELECT COUNT(*) FROM service","Services_Count"));
        jLabel8.setText(PredefineMethods.viewDBValue("SELECT COUNT(service_no) as service_no FROM service", "service_no"));
        vehiclelbl.setText(PredefineMethods.viewDBValue("SELECT COUNT(vehicle_no) as vehicle_no FROM vehicle", "vehicle_no"));
        jLabel10.setText(PredefineMethods.viewDBValue("SELECT COUNT(machine_ref_no) as machine_ref_no FROM repair WHERE repair_status='Available'", "machine_ref_no"));
        jLabel7.setText(PredefineMethods.viewDBValue("SELECT COUNT(epfNo) as empCount FROM employee WHERE availability='Available'", "empCount"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        att = new javax.swing.JLabel();
        repairList = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mac = new javax.swing.JLabel();
        empAvailable = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ve = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serviceList = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        vehiclelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(940, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 220, 90));

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CurrentProcess.png"))); // NOI18N
        status.setText("jLabel4");
        status.setFocusCycleRoot(true);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statusMousePressed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 130));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Status");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 20));

        att.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        att.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(att, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 70, 20));

        repairList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MachineRepair.png"))); // NOI18N
        repairList.setText("jLabel4");
        repairList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repairListMousePressed(evt);
            }
        });
        jPanel1.add(repairList, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 130, 130));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Machines to be Repaired :-");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 150, 20));

        mac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mac.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(mac, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 70, 20));

        empAvailable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EmployeeAttendance.png"))); // NOI18N
        empAvailable.setText("jLabel4");
        empAvailable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empAvailableMousePressed(evt);
            }
        });
        jPanel1.add(empAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, 130));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Today's Employee Attendance :-");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 180, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 65, 65));
        jLabel6.setText("Critical Level Chemical Stocks");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 220, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Machines to be Service :-");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, 20));

        ve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ve.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 730, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 390, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 40));

        serviceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VehicleAvailable.png"))); // NOI18N
        serviceList.setText("jLabel4");
        serviceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                serviceListMousePressed(evt);
            }
        });
        jPanel1.add(serviceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 130));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Attend");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 40, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Service");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 50, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Machine");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 50, 20));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(248, 65, 65));
        jLabel11.setText("Critical Level Fertilizer Stocks");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 220, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 220, 90));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vehicles :-");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, 20));

        vehiclelbl.setForeground(new java.awt.Color(255, 255, 255));
        vehiclelbl.setText("vehicle");
        jPanel1.add(vehiclelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DashboardBackground.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(940, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(940, 480));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMousePressed
        new ViewStatus().setVisible(true);
    }//GEN-LAST:event_statusMousePressed

    private void serviceListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceListMousePressed
        new VehiclesSummary().setVisible(true);
    }//GEN-LAST:event_serviceListMousePressed

    private void repairListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repairListMousePressed
        new MachineDetails().setVisible(true);
    }//GEN-LAST:event_repairListMousePressed

    private void empAvailableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empAvailableMousePressed
        new AvailableEmployees().setVisible(true);
    }//GEN-LAST:event_empAvailableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel att;
    private javax.swing.JLabel empAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel mac;
    private javax.swing.JLabel repairList;
    private javax.swing.JLabel serviceList;
    private javax.swing.JLabel status;
    private javax.swing.JLabel ve;
    private javax.swing.JLabel vehiclelbl;
    // End of variables declaration//GEN-END:variables
}
